name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Configure Git identity
      run: |
        git config --local user.name "bot"
        git config --local user.email "bot@github.com"


    - name: Build
      run: |
        npm ci
        npm run build
        git add .
        git commit -m 'feat: update'
        git push

